### PR TITLE
Improved delay behavior after promotion based on feedback.

### PR DESCRIPTION
**Pull request by vitroth**
@philpennock

### CODE REVIEW

**Comment by philpennock** [comment]
Uhm, I forgot one important line.  `sleep 1` inside the loop.

**Comment by philpennock** [comment]
Also, die is not a standard function, sorry.  It's something I commonly create at the top of a script.

```
if [[ $okay == f ]]; then
  echo >&2 "Postgres never entered read-write mode after promotion from replica to master"
  exit 1
fi
```

**Comment by philpennock** [comment]
LGTM with those fixes applied, but not as-is now.

**Comment by vitroth** [comment]
Corrected the sleep and failure behaviors, and added output logging of progress and success. 

PTAL @philpennock

**Comment by philpennock** [comment]
LGTM

**Pull request merged**
