### PR TITLE
Enable customization of some postgresql settings related to autovacuum and checkpointing (write ahead log)

### PR DESCRIPTION
**Pull request by tmlink**
Enabling changing the postgreSQL configuration setting related to
auto_vacuum and checkpointing (write ahead log)

The default values remain the same.
This just allows the defaults to be overridden.

### CODE REVIEW

**Comment by tmlink** [comment]
replacement for pull/3.
removed all the extra stuff
@philpennock & @vitroth -- please review

**Comment by philpennock** [comment]
LGTM.  I'm a little apprehensive about floating point values being passed around for interpolation; it works with `0.5` and some other common values ... but this is a broader cookbook issue, not specific to this change except insofar as you're exposing it.  Just keep an eye on this as you adjust the cookbook, see if some of these constant values can be strings instead of floats?

**Comment by tmlink** [comment]
Modified file to enable the customization of two settings.  'autovacuum_vacuum_scale_factor' and 'autovacuum_analyze_scale_factor'.  

Pleae review:  @philpennock and @vitroth

**Comment by philpennock** [comment]
Changes LGTM but please squash before merge: we don't need three different commits for this little change.  `git rebase -i origin/master`

**Comment by vitroth** [comment]
==phil, and also please change the PR title to be descriptive.  This is a public repo, we shouldn't reference internal tickets in PR titles, but instead describe the intent of the change.  (IMO we should always do that, as it makes browsing the PR history in github more useful)

**Comment by tmlink** [comment]
Now we have 5 commits...

  631  git rebase -i origin/master
p older
s newer
  632  git status
  633  git push origin tomlink-enable-config-vals  # want a pull first
  634  git pull  origin tomlink-enable-config-vals
  635  git push  origin tomlink-enable-config-vals

**Comment by vitroth** [comment]
After a rebase you need to force push, i.e. `git push origin +tomlink-enable-config-vals`

You also might want to use 'fixup' over 'squash' in your rebase

**Comment by tmlink** [comment]
1 -> 3 -> 5 -> 7 -> 1

@vitroth please review for pull.

**Comment by vitroth** [comment]
LGTM

**Comment by tmlink** [comment]
Thanks for your patience and all of your help.  I took notes.  Pulling.

**Pull request merged**
