### PR TITLE
Updated postgres version to 9.4.

### PR DESCRIPTION
**Pull request by vitroth**
Added upgrade recipe for triggering a postgres upgrade. To enable, the
caller must set node[:postgresql][:enable_upgrade_from_version_and_yes_i_have_a_backup]
to the version number of the existing database to be migrated, i.e "9.3".

The upgrade recipe will require there to be 3X the current database's
disk usage available on the filesystem where the new database will be
created.  If the upgrade fails the old database will be brought back
online.

I'm still doing testing to watch for edge conditions.  I had a successful upgrade of the Zabbix database, where I had imported a gig of data from another cluster (resulting in a 4.5G postgres data directory).  The backup and upgrade took approx 45 minutes to run, but orchestrator did not time out and everything ran as expected.

Reviewers: @philpennock @shr3kst3r @austinmills

### CODE REVIEW

**Comment by philpennock** [comment]
At what point is the old version's data on disk deleted?  Is that the drop stuff in the upgrade script?

If there are a pair of servers, A and B, and the Chef run fails after migrating A but before completing B, I think that this leaves us unable to finish the run, because A will fatal out on the second run and might stop B from happening.

So I think that the fatal needs to downgrade into a warning, and we need another approach to prevent this version being left around.  Grossest but safest might be to drop a flag-file saying "we've done 9.3 to 9.4" and if that flagfile exists for this version migration and is less than a week old, then don't fatal out.

**Comment by vitroth** [comment]
Old data is deleted by the drop command.

Assuming A is the master and B is the slave, and on the first pass A upgrades but we abort before B, on the next run the following would occur:

On A it would already have PG 9.4 running, and the 9.3 detection code would not see an old 9.3 data directory, so it just goes on about its business as a 9.4 server.

On B the detection code would see the old 9.3 data directory, run a backup and delete the directory.  Then the postgres cookbook would initialize the data directory by run the pg_basebackup command and restart replication.

**Comment by philpennock** [comment]
That does not match my parsing of `recipes/data_directory.rb` and the line 26 fatal reached if (1) we are the master, (2) the magic flag is set, (3) the old directory no longer exists.  With this recipe file pulled in from `recipes/server.rb` unconditionally.

Separately: what happens if the secondary is upgraded first, such that you get a 9.4 secondary replicating from a 9.3 master?  Does everything end up okay after the master moves to 9.4 too?  What about replication xlogs, etc?

**Comment by vitroth** [comment]
On the second pass is the old data directory is gone the magic flag will not be set.  The existence of that directory is what I'm using to trigger setting the flag in the calling recipes.

**Comment by vitroth** [comment]
The secondary will never be upgraded first, as the deploy script runs the component-database-master and auditlog-database-master roles before running the generic role.

**Comment by philpennock** [comment]
Re secondary/primary: good, thanks.

Re magic flag: ah right, is in the `continuum-chef` repo, I was only looking here.  It was set in the other PR I reviewed, sorry.  Had it in my head that this was set in the cluster.conf manually to trigger an update when ready.

LGTM.

**Comment by vitroth** [comment]
Updated to bundle the sys-filesystem gem that I'm using to calculate disk space.

**Comment by philpennock** [comment]
Why are you bundling the binary asset (which is what a gem becomes) in this way?

Clients of this cookbook can use their own gem bundling systems.  We have our own in-house system elsewhere.  Why does this gem belong as a binary asset in _this_ chef cookbook repo?

**Comment by philpennock** [comment]
LGTM, internal ticket filed for a better way.

**Comment by vitroth** [comment]
Reduced the requirement for available disk space from 3x the current size of the postgres data directory to 2x, based on testing.

PTAL for final review: @philpennock

**Comment by philpennock** [comment]
LGTM

**Comment by vitroth** [comment]
Addresses #SRE-428

**Pull request merged**
